import type { CalendarEvent } from '@momeants/types';

const THIS_YEAR = new Date().getFullYear();

export const DEMO_CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: 'ce-1',
    type: 'birthday',
    title: "Ava's Birthday",
    date: `${THIS_YEAR}-11-22`,
    isRecurring: true,
    personId: 'u5',
    personName: 'Ava Chen',
    personAvatarUri: 'https://i.pravatar.cc/150?u=ava',
    emoji: '🎂',
  },
  {
    id: 'ce-2',
    type: 'birthday',
    title: "Noah's Birthday",
    date: `${THIS_YEAR}-12-03`,
    isRecurring: true,
    personId: 'u6',
    personName: 'Noah Kim',
    personAvatarUri: 'https://i.pravatar.cc/150?u=noah',
    emoji: '🎂',
  },
  {
    id: 'ce-3',
    type: 'anniversary',
    title: 'Anniversary with Alex',
    description: '2 years ♡',
    date: `${THIS_YEAR}-11-28`,
    isRecurring: true,
    recurringYear: 2022,
    personId: 'u8',
    personName: 'Alex Rivera',
    personAvatarUri: 'https://i.pravatar.cc/150?u=alex',
    emoji: '💑',
  },
  {
    id: 'ce-4',
    type: 'memory_anniversary',
    title: 'Mountain Campfire Trip',
    description: '1 year ago today',
    date: `${THIS_YEAR}-11-10`,
    isRecurring: true,
    recurringYear: 2023,
    momentId: '1',
    emoji: '🏕️',
  },
  {
    id: 'ce-5',
    type: 'holiday',
    title: 'Thanksgiving',
    date: `${THIS_YEAR}-11-28`,
    isRecurring: true,
    emoji: '🦃',
  },
  {
    id: 'ce-6',
    type: 'holiday',
    title: 'Christmas',
    date: `${THIS_YEAR}-12-25`,
    isRecurring: true,
    emoji: '🎄',
  },
  {
    id: 'ce-7',
    type: 'clique_event',
    title: 'Game Night @ Mia\'s',
    date: `${THIS_YEAR}-11-22`,
    isRecurring: false,
    cliqueId: 'clique-besties',
    cliqueName: 'The Crew',
    emoji: '🎲',
  },
  {
    id: 'ce-8',
    type: 'birthday',
    title: "Mom's Birthday",
    date: `${THIS_YEAR}-12-14`,
    isRecurring: true,
    personId: 'u2',
    personName: 'Mom Ellis',
    personAvatarUri: 'https://i.pravatar.cc/150?u=mom',
    emoji: '🎂',
  },
];
