import type { SponsoredItem } from '@momeants/types';

export const MOCK_SPONSORED_ITEMS: SponsoredItem[] = [
  {
    id: 'ad_001',
    advertiserId: 'tintype_studio',
    advertiserName: 'Tintype Studio',
    headline: 'Turn your moments into prints.',
    subtext: 'Premium photo books, starting at $19.',
    imageUri: 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800',
    ctaLabel: 'Shop Prints',
    ctaUrl: 'https://example.com',
    category: 'photography',
    targetInterests: ['photography', 'family', 'gifting'],
    impressionCap: 3,
    active: true,
  },
  {
    id: 'ad_002',
    advertiserId: 'wander_collective',
    advertiserName: 'Wander Collective',
    headline: 'Your next adventure is waiting.',
    subtext: 'Curated travel experiences for people who collect memories.',
    imageUri: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800',
    ctaLabel: 'Explore Trips',
    ctaUrl: 'https://example.com',
    category: 'travel',
    targetInterests: ['travel', 'wellness'],
    impressionCap: 2,
    active: true,
  },
  {
    id: 'ad_003',
    advertiserId: 'bloom_gifts',
    advertiserName: 'Bloom & Co.',
    headline: 'Something special for someone special.',
    subtext: 'Gifts that feel personal. Free delivery over $40.',
    imageUri: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800',
    ctaLabel: 'Browse Gifts',
    ctaUrl: 'https://example.com',
    category: 'gifting',
    targetInterests: ['gifting', 'family'],
    targetRelationshipTypes: ['family', 'romantic_partner', 'best_friend'],
    impressionCap: 3,
    active: true,
  },
  {
    id: 'ad_004',
    advertiserId: 'soulground',
    advertiserName: 'Soulground',
    headline: 'Mindful mornings, better memories.',
    subtext: 'Journaling + meditation for the moments between moments.',
    ctaLabel: 'Try Free',
    ctaUrl: 'https://example.com',
    category: 'wellness',
    targetInterests: ['wellness'],
    impressionCap: 2,
    active: true,
  },
  {
    id: 'ad_005',
    advertiserId: 'feast_box',
    advertiserName: 'Feast Box',
    headline: 'Cook the meal. Share the moment.',
    subtext: 'Weekly meal kits designed for quality time.',
    imageUri: 'https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=800',
    ctaLabel: 'Get Started',
    ctaUrl: 'https://example.com',
    category: 'food',
    targetInterests: ['food', 'family'],
    impressionCap: 2,
    active: true,
  },
];
